# -- SOURCE: https://github.com/marketplace/actions/setup-python
# SEE: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# SUPPORTED PYTHON VERSIONS: https://github.com/actions/python-versions

name: tests
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    # -- EXAMPLE: runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # PREPARED: os: [ubuntu-latest, macos-latest, windows-latest]
        # PREPARED: python-version: ['3.9', '2.7', '3.10', '3.8', 'pypy-2.7', 'pypy-3.8']
        # PREPARED: os: [ubuntu-latest, windows-latest]
        # MERKER: python-version: ["3.11", "3.10", "3.9", "2.7"]
        os: [ubuntu-latest]
        python-version: ["3.11", "3.10"]
        exclude:
          - os: windows-latest
            python-version: "2.7"
    steps:
      - uses: actions/checkout@v3
      # DISABLED: name: Setup Python ${{ matrix.python-version }} on platform=${{ matrix.os }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'py.requirements/*.txt'
      # -- DISABLED:
      # - name: Show Python version
      #  run: python --version
      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -U -r py.requirements/ci.github.txt
          pip install -e .
      - name: Run tests
        run: pytest
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test reports
          path: |
            build/test_report.xml
            build/test_report.html
        if: ${{ job.status == 'failure' }}
        # MAYBE: if: ${{ always() }}
